### ISSUE TITLE
Inaccurate data for two-key briefs

### ISSUE THREAD

**Issue by jameschensmith** [didoesdigital/typey-type-data#5]
**Details**

I believe I found some inaccurate data while working through the two-key briefs. I'm still new to stenography, so I could be wrong. Following the current contributing process for submitting inaccurate data to look into.

**List of folders & chords to investigate**

- `lessons/collections/two-key-briefs/two-key-briefs--F`
  - `TP-PL` - Should be removed.
- `lessons/collections/two-key-briefs/two-key-briefs--P`
  - `WR` - Should be removed.
- `lessons/collections/two-key-briefs/two-key-briefs--R`
  - `TR` - Remove or replace with `T-R`.
  - `KR` - Remove or replace with `K-R`.
  - `WR` - Should be removed.
- `lessons/collections/two-key-briefs/two-key-briefs--T`
  - `OR` - Should be removed.
- `lessons/collections/two-key-briefs/two-key-briefs-A`
  - `HRO*ER/PA` - Should be removed or replaced with `PA` ("Pa").
- `lessons/collections/two-key-briefs/two-key-briefs-O`
  - `#-Z` - Should be removed.
- `lessons/collections/two-key-briefs/two-key-briefs-P`
  - `HRO*ER/PA` - Should be removed or replaced with `PA` ("Pa").
- `lessons/collections/two-key-briefs/two-key-briefs-R`
  - `-RL` - Should be removed.
  - `-RT` - Should be removed.

**Comment by didoesdigital** [comment]
Thanks so much for putting together this list! That's really helpful for me. Yes, they look inaccurate; I think some are due to changes between old and newer Plover dictionary versions and this collection hasn't been updated to match. When I have a moment I'll work through them and get the changes published. Thanks again!

**Comment by didoesdigital** [comment]
And it's live! Where you suggested multiple options @jameschensmith , I opted to remove the entries just because it was convenient given how the scripts work.

Here's an example of an updated lesson that no longer includes the flagged entry: [Two-key briefs *-R](https://didoesdigital.com/typey-type/lessons/collections/two-key-briefs/two-key-briefs--R/ )

Thanks again for filing the issue, and for outlining it so clearly that it was very easy to implement.
